import "server-only";

/**
 * Portal i18n. Small dictionary kept inline instead of leaning on the
 * marketing i18n setup: the portal copy is finite and scoped, so a flat
 * object is the simplest source of truth.
 *
 * Resolution order:
 *   1. client_portal_access.preferred_language  (if set by the client)
 *   2. engagements.language                     (defaults to 'en')
 *   3. 'en'                                     (hard fallback)
 *
 * Plurals: a count-dependent phrase lives under two keys, `<key>.one` and
 * `<key>.other`, read through tn(). Never build plurals by appending a
 * suffix: Spanish changes the stem ("acción" / "acciones").
 */

export type PortalLang = "en" | "es";

type Dict = Record<string, string>;

const EN: Dict = {
  // Sidebar
  "nav.bandeja": "Inbox",
  "nav.customers": "Customers",
  "nav.settings": "Settings",
  "nav.support": "Support",
  "nav.sign_out": "Sign out",
  "nav.portal": "Portal",
  "session.7day": "7-day session",
  "footer.audit": "Every decision is logged in our append-only audit chain.",

  // One-tap language toggle
  "lang.toggle_label": "Portal language",
  "lang.switch_en": "Show the portal in English",
  "lang.switch_es": "Show the portal in Spanish",

  // Resumen
  "resumen.greeting": "Hello, {name}",
  "resumen.you": "you",
  "resumen.cta_view_inbox": "Open inbox",
  "resumen.status_title": "Service status",

  // Money button
  "money.alert_title.one": "{n} approval waiting on you",
  "money.alert_title.other": "{n} approvals waiting on you",

  // Incident severity
  "severity.critical": "Critical",
  "severity.high": "High",
  "severity.medium": "Medium",
  "severity.low": "Low",

  // Today agenda widget
  "today.title": "Today on the calendar",
  "today.empty": "No appointments today yet.",
  "today.more": "+{n} more later today",

  // Live activity widget
  "live.empty": "Once customers start writing to your agent, you'll see it here.",

  // Inbox
  "inbox.title": "Inbox",
  "inbox.desc": "Every conversation between your customers and your agent.",
  "inbox.count.one": "{n} conversation in the last 30 days.",
  "inbox.count.other": "{n} conversations in the last 30 days.",
  "inbox.empty_title": "No conversations yet",
  "inbox.empty_desc": "When someone writes to your agent, the conversation shows up here.",
  "inbox.disabled_title": "Inbox not turned on yet",
  "inbox.disabled_desc": "Conversation history is not turned on for your account yet. Write to contact@loucellscore.com and we'll turn it on.",
  "inbox.select_one": "Pick a conversation from the left.",
  "inbox.filter_all": "All",
  "inbox.tags_label": "Tags",
  "inbox.agent_prefix": "Agent: ",
  "inbox.you_prefix": "You: ",
  "inbox.messages.one": "{n} message",
  "inbox.messages.other": "{n} messages",
  "inbox.message_unavailable": "[message unavailable]",
  "inbox.tag_filter": "Filter by tag",
  "inbox.take_over": "Take over",
  "inbox.take_over_active": "You're driving this conversation",
  "inbox.take_over_release": "Release back to agent",
  "inbox.send": "Send",
  "inbox.sending": "Sending…",
  "inbox.composer_placeholder": "Type your message…",
  "inbox.agent_paused": "Agent paused. You're handling this conversation manually.",
  "inbox.sent_email": "Sent by email.",
  "inbox.not_delivered_no_contact": "Not delivered: this customer left no email.",
  "inbox.not_delivered_failed": "Not delivered: the email could not be sent. Try again in a minute.",
  "inbox.no_contact_notice": "You can't reply from here: this customer left no email, so your message would never reach them.",

  "tag.complaint": "Complaint",
  "tag.booking": "Booking",
  "tag.info_request": "Info request",
  "tag.follow_up": "Follow up",
  "tag.spam": "Spam",
  "tag.vip": "VIP",
  "tag.urgent": "Urgent",
  "tag.sale_lost": "Sale lost",
  "tag.sale_won": "Sale won",

  // Message labels shown in the inbox and live feed (from tool summaries)
  "tool.sent_by": "Sent by {name}",
  "tool.escalated": "Passed to your team",
  "tool.booked": "Booking for {name}",
  "tool.refund_blocked": "Refund to a new recipient blocked",
  "tool.approval_requested": "Sent to you for approval",
  "tool.approval_skipped": "Approval request not created",

  // Shared error copy (client components receive these as props)
  "error.network": "No connection. Check your internet and try again.",
  "error.rate_limited": "Too many attempts. Wait a few minutes and try again.",
  "error.unauthorized": "Your session ended. Sign in again.",
  "error.not_found": "We couldn't find this anymore. Refresh the page.",
  "error.bad_request": "We couldn't read that. Check the text and try again.",
  "error.service_unavailable": "The service is not available right now. Try again in a few minutes.",
  "error.generic": "Something went wrong. Try again or write to contact@loucellscore.com.",

  // Requires action
  "ra.title": "Approvals",
  "ra.subtitle_pending.one": "{n} action waiting for your go-ahead.",
  "ra.subtitle_pending.other": "{n} actions waiting for your go-ahead.",
  "ra.subtitle_empty": "Nothing to decide right now.",
  "ra.subtitle_no_agent": "When your agent needs your OK before sending something, it shows up here.",
  "ra.history_title": "Decision history",
  "ra.history_eyebrow": "Last 20",
  "ra.clear_title": "All clear",
  "ra.clear_desc": "Nothing is waiting on you.",
  "ra.action.send_message": "Send message",
  "ra.action.send_quote": "Send quote",
  "ra.action.send_refund": "Process refund",
  "ra.action.reply_review": "Reply to review",
  "ra.action.other": "Agent action",
  "ra.high_risk": "High risk",
  "ra.medium_risk": "Medium risk",
  "ra.proposed_label": "What the agent wants to send:",
  "ra.edit_label": "Edit the message",
  "ra.reject_label": "Why? (optional)",
  "ra.reject_placeholder": "I'll write it myself / wrong info / not ready yet",
  "ra.btn_approve": "Approve and send",
  "ra.btn_modify": "Modify",
  "ra.btn_reject": "Reject",
  "ra.btn_approve_edited": "Approve edited version",
  "ra.btn_confirm_reject": "Confirm rejection",
  "ra.btn_cancel": "Cancel",
  "ra.btn_back": "Back",
  "ra.sending": "Sending…",
  "ra.approving": "Approving…",
  "ra.rejecting": "Rejecting…",
  "ra.realtime_hint": "Sends instantly via email",
  "ra.stub_hint": "Confirmation within 1 business hour",
  "ra.approved_realtime": "Sent",
  "ra.approved_stub": "Approved",
  "ra.approved_realtime_desc": "Message went out immediately.",
  "ra.approved_stub_desc": "We're carrying it out. You'll get a confirmation within 1 business hour.",
  "ra.rejected": "Rejected",
  "ra.rejected_desc": "Your agent will not send this action.",
  "ra.already_title": "Already handled",
  "ra.already_desc": "This action was already approved or rejected.",
  "ra.error": "We couldn't process the action. Try again or email contact@loucellscore.com.",
  "ra.error_edit_pii": "Your edit contains sensitive data ({types}) that can't go out by email. Remove it and try again.",

  // Risk chips on approval cards
  "risk.contains_link": "Contains a link",
  "risk.recipient_unverified": "Recipient not mentioned by the customer",
  "risk.pii": "Contains {type}",

  // Sensitive data types
  "pii.ssn": "a Social Security number",
  "pii.ein": "a tax ID (EIN)",
  "pii.itin": "a tax ID (ITIN)",
  "pii.credit_card": "a card number",
  "pii.email": "an email address",
  "pii.us_phone": "a phone number",
  "pii.api_key": "an access key",
  "pii.other": "personal data",

  // Customers
  "customers.title": "Customers",
  "customers.desc": "Everyone who has written to your agent, by website chat or by text.",
  "customers.empty_title": "No customers yet",
  "customers.empty_desc": "When people start writing to your agent, each one shows up here with their history.",
  "customers.count.one": "{n} person",
  "customers.count.other": "{n} people",
  "customers.col_sessions": "Sessions",
  "customers.col_bookings": "Bookings",

  // Customer detail
  "customer.back": "All customers",
  "customer.history_title": "Conversation history",
  "customer.bookings_title": "Bookings",
  "customer.notes_title": "Internal notes",
  "customer.notes_empty": "No notes yet. Add one any time.",
  "customer.notes_error": "Couldn't save the note. Try again.",
  "customer.seen": "First seen {first} · Last seen {last}",
  "customer.channels": "Channels",
  "customer.entries.one": "{n} entry",
  "customer.entries.other": "{n} entries",
  "customer.no_conv_title": "No conversations yet",
  "customer.no_conv_desc": "When this customer writes again, it shows up here.",
  "customer.no_reason": "No reason captured",
  "customer.channel": "Channel: {channel}",
  "customer.open_chat": "Open conversation",
  "customer.confirmed_count.one": "{n} confirmed",
  "customer.confirmed_count.other": "{n} confirmed",
  "customer.no_bookings": "No bookings yet",
  "customer.confirmed_on": "Confirmed {date}",
  "customer.confirmed": "Confirmed",

  // Channels
  "channel.web_chat": "Website chat",
  "channel.website": "Website form",
  "channel.sms": "Text messages",
  "channel.whatsapp": "WhatsApp",
  "channel.email": "Email",
  "channel.phone": "Phone",
  "channel.gbp": "Google reviews",
  "channel.slack": "Slack",
  "channel.other": "Other",

  // Agents
  "agents.empty_title": "No agents yet",
  "agents.empty_desc": "When Loucells Core sets up an agent for you, it shows up here with what it does and the results it gets.",

  "agent_status.designing": "Being set up",
  "agent_status.shadow_mode": "Learning",
  "agent_status.uat": "Testing",
  "agent_status.live": "Live",
  "agent_status.paused": "Paused",
  "agent_status.archived": "Retired",
  "agent_status.other": "In progress",

  "agent_type.ai_front_desk": "Front desk",
  "agent_type.quote_accelerator": "Quotes",
  "agent_type.review_manager": "Reviews",
  "agent_type.operations_gap_audit": "Operations review",
  "agent_type.custom": "Custom agent",

  "integration.calendar": "Calendar",
  "integration.booking": "Booking system",
  "integration.crm": "CRM",
  "integration.reminders": "Appointment reminders",
  "integration.whatsapp": "WhatsApp",
  "integration.sms": "Text messages",
  "integration.email": "Email",
  "integration.payments": "Payments",
  "integration.reviews": "Reviews",

  // Activity log (audit rows, translated from a whitelist)
  "audit.ev.user_message": "Customer message received",
  "audit.ev.assistant_reply": "Agent replied",
  "audit.ev.escalation": "Passed to your team",
  "audit.ev.booking_offered": "Booking link sent",
  "audit.ev.approval_requested": "Sent to you for approval",
  "audit.ev.queue_full": "Too many actions waiting for your approval",
  "audit.ev.hitl_approved": "You approved an action",
  "audit.ev.hitl_rejected": "You rejected an action",
  "audit.ev.action_failed": "An approved action could not be completed",
  "audit.ev.take_over": "You replied personally",
  "audit.ev.paused": "Agent paused while you handle the conversation",
  "audit.ev.sensitive_blocked": "Message with sensitive data blocked",
  "audit.ev.sensitive_hidden": "Sensitive data hidden",
  "audit.ev.rate_limited": "Too many messages in a short time",
  "audit.ev.origin_blocked": "Blocked from a website that isn't yours",
  "audit.ev.unavailable": "The agent couldn't reply",
  "audit.ev.hard_rule": "Reply adjusted by safety rules",
  "audit.ev.refund_blocked": "Refund to a new recipient blocked",
  "audit.ev.config_update": "Agent settings updated",
  "audit.ev.other": "System event",
  "audit.src.agent": "Agent",
  "audit.src.portal": "Portal",
  "audit.src.hitl": "Approvals",
  "audit.src.dlp": "Data protection",
  "audit.src.webhook": "Connected tool",
  "audit.src.security": "Security",
  "audit.src.other": "System",

  // Analytics
  "analytics.hourly_title": "When customers reach out",
  "analytics.hourly_desc": "Customer messages by hour of your day.",
  "analytics.topics_title": "What they ask about",
  "analytics.topics_desc": "Grouped by the first message of each conversation.",

  // Settings
  "settings.title": "Settings",
  "settings.desc": "Your plan, your agent and the portal language.",
  "settings.tab_billing": "Plan",
  "settings.tab_language": "Language",
  "settings.plan_title": "Your Loucells Core plan",
  "settings.plan_eyebrow": "Monthly summary",
  "settings.plan_monthly": "Monthly cost",
  "settings.plan_monthly_sub": "Flat monthly fee. Hosting, maintenance and support included.",
  "settings.plan_agents": "Agents included",
  "settings.plan_client_since": "Customer since",
  "settings.plan_portal_activated": "Portal activated {date}",
  "settings.includes_title": "What's included",
  "settings.includes_eyebrow": "Included in your plan",
  "settings.account_title": "Account details",
  "settings.account_eyebrow": "Contact info",
  "settings.account_legal": "Legal name",
  "settings.account_vertical": "Vertical",
  "settings.account_language": "Language",
  "settings.account_email": "Billing email",
  "settings.account_update": "Update info",
  "settings.billing_help": "Questions about your invoice? Write to contact@loucellscore.com.",
  "settings.lang_title": "Display language",
  "settings.lang_desc": "Applies to every page in this portal.",
  "settings.lang_en": "English",
  "settings.lang_es": "Spanish",
  "settings.lang_save": "Save preference",
  "settings.lang_saved": "Saved",

  // Login
  "login.title": "Welcome back",
  "login.desc": "Enter the passcode Loucells Core shared with you to access your portal.",
  "login.inside": "What you'll see inside",
  "login.inside_conversations": "Your conversations",
  "login.inside_approvals": "Approvals",
  "login.inside_customers": "Your customers",
  "login.inside_log": "Activity log",
  "login.passcode": "Passcode",
  "login.placeholder": "Paste the passcode here",
  "login.submit": "Enter portal",
  "login.submitting": "Signing in…",
  "login.err_rate": "Too many attempts. Please try again in a few minutes.",
  "login.err_bad": "That passcode doesn't match. Check the message Loucells Core sent you.",
  "login.err_generic": "We couldn't sign you in. Try again or email contact@loucellscore.com.",
  "login.err_network": "No connection. Check your internet and try again.",
  "login.footnote": "Your session lasts 7 days. Conversations are stored encrypted, and personal data is masked before it reaches the activity log.",

  // Common
  "btn.save": "Save",

  // Mobile nav
  "nav.open_menu": "Open menu",
  "nav.close_menu": "Close menu",

  // ── Portal v3 (5 pages) ────────────────────────────────────────────
  "nav.home": "Home",
  "nav.approvals": "Approvals",

  "home.eyebrow": "Last {n} days",
  "home.desc": "What needs you comes first. Below it, what your agent did for {client}.",
  "home.needs_title": "Needs you",
  "home.needs_clear": "Nothing needs you right now.",
  "home.needs_clear_desc": "Your agent is handling everything within the rules you approved.",
  "home.see_all.one": "See {n} approval",
  "home.see_all.other": "See all {n} approvals",
  "home.escalations.one": "{n} customer needs a person",
  "home.escalations.other": "{n} customers need a person",
  "home.takeovers.one": "{n} conversation you're handling",
  "home.takeovers.other": "{n} conversations you're handling",
  "home.takeover_hint": "Your agent stays quiet in these until you hand them back.",
  "home.open": "Open",
  "home.recent_title": "Recent conversations",
  "home.insights_eyebrow": "Last 30 days",
  "home.peak_hour": "Busiest hour: {hour}",

  "badge.web": "Web",
  "badge.sms": "Text",

  "topic.booking": "Booking",
  "topic.pricing": "Prices",
  "topic.hours": "Hours and location",
  "topic.service_info": "Questions about a service",
  "topic.complaint": "Problems or complaints",
  "topic.other": "Other",

  "escalation.reason.out_of_scope": "Asked about something your agent doesn't handle",
  "escalation.reason.sensitive_topic": "A sensitive topic",
  "escalation.reason.frustrated_visitor": "The customer seems upset",
  "escalation.reason.ambiguous_high_stakes": "An important request that needs your call",
  "escalation.reason.agent_uncertain": "Your agent wasn't sure how to answer",
  "escalation.reason.other": "Needs a person",

  "inbox.filter_taken": "Taken over",
  "inbox.filter_urgent": "Urgent",
  "inbox.filter_booked": "Booked",
  "inbox.any_tag": "Any tag",
  "inbox.filter_empty": "No conversations match this filter.",
  "inbox.window_empty": "No conversations in the last 30 days.",
  "inbox.web_visitor": "Website visitor",
  "inbox.back": "All conversations",
  "inbox.sms_readonly": "Reply from your phone for now.",
  "inbox.text_customer": "Text {phone}",
  "inbox.not_delivered": "Not delivered",
  "inbox.badge_taken": "You're handling it",
  "inbox.badge_urgent": "Urgent",
  "inbox.not_found": "We couldn't find this conversation. It may be older than 30 days.",

  "ra.open_conversation": "Open conversation",
  "ra.outcome.sent": "Sent",
  "ra.outcome.handling": "Handling",
  "ra.outcome.failed": "Failed",
  "ra.outcome.rejected": "Rejected",
  "ra.history_note": "Sent: it went out. Handling: we're carrying it out for you. Failed: it didn't go out, write to contact@loucellscore.com.",

  "customers.conversations.one": "{n} conversation",
  "customers.conversations.other": "{n} conversations",
  "customers.bookings.one": "{n} booking",
  "customers.bookings.other": "{n} bookings",
  "customers.last_contact": "Last contact {date}",
  "customers.no_name": "No name yet",

  "customer.text_title": "Text messages",
  "customer.open_texts": "Open text conversation",
  "customer.appt.scheduled": "Scheduled",
  "customer.appt.confirmed": "Confirmed",
  "customer.appt.completed": "Done",
  "customer.appt.cancelled": "Cancelled",
  "customer.appt.no_show": "Didn't show up",

  "settings.tab_agent": "Your agent",
  "settings.agent_live_since": "Live since {date}",
  "settings.agent_connections": "Connected tools",
  "settings.conn_connected": "Connected",
  "settings.conn_missing": "Not connected yet",
  "settings.conn_since": "Since {date}",
  "settings.conn_none": "No tools connected yet.",
  "settings.conn_missing_help": "We connect these with you. Write to contact@loucellscore.com.",
  "settings.agent_change": "Want to change something? Write to contact@loucellscore.com.",

  "conn.sms": "Text messages",
  "conn.booking_system": "Your booking system",
  "conn.reviews": "Google reviews",
  "conn.payments": "Payments",
  "conn.crm": "Customer list (CRM)",
  "conn.accounting": "Accounting",
  "conn.field_service": "Job management",
  "conn.email": "Email",
  "conn.microsoft": "Microsoft email and calendar",
  "conn.other": "Other tool",

  "embed.title": "Website chat code",
  "embed.desc": "Paste it just before </body> on any page where you want the chat.",
  "embed.live": "Live",
  "embed.not_live": "Not live yet",
  "embed.copy": "Copy",
  "embed.copied": "Copied",
  "embed.copy_aria": "Copy the code",
  "embed.domains": "Websites where it works",
  "embed.domains_desc": "The chat only loads on these websites. To add or remove one, write to us.",
  "embed.domains_none": "No websites added yet. The chat won't load until we add at least one.",
  // ── Results (Home, value in money and outcomes) ───────────────────
  "home.results_title": "Results",
  "home.window_label": "Period",
  "home.window_days": "{n} days",
  "value.bookings": "Bookings from your agent",
  "value.revenue": "Revenue from completed bookings",
  "value.conversations": "Conversations",
  "value.window_sub": "Last {n} days",
  "value.rule": "Revenue counts only completed appointments where the customer talked to your agent first. Bookings protected by a reminder are counted separately and never added to revenue.",
  "value.unpriced.one": "{n} appointment in this period has no price, so its value isn't counted.",
  "value.unpriced.other": "{n} appointments in this period have no price, so their value isn't counted.",
  "value.after_hours.one": "After business hours: {a} of {n} conversation.",
  "value.after_hours.other": "After business hours: {a} of {n} conversations.",
  "value.reply_time": "Usual reply time to texts: {time}.",
  "value.seconds.one": "{n} second",
  "value.seconds.other": "{n} seconds",
  "value.minutes.one": "{n} minute",
  "value.minutes.other": "{n} minutes",
  "value.hours_estimate": "About {h} hours of front desk work saved. Estimate: {n} min per conversation.",
  "value.hours_estimate_mixed": "About {h} hours of front desk work saved (estimate).",
  "value.unavailable": "We couldn't load these numbers right now. Refresh in a minute.",

  // Front desk results
  "fd.title": "Front desk results",
  "fd.reminders_sent": "Reminders sent",
  "fd.kept": "Kept",
  "fd.no_shows": "No-shows",
  "fd.no_show_rate": "No-show rate",
  "fd.rate_none": "Not yet",
  "fd.note": "Kept and no-shows are appointments that got a reminder. The no-show rate covers every finished appointment in this period.",
  "fd.protected": "Bookings protected by a reminder: {n}. Counted here, never added to revenue.",
  "fd.before_now": "No-shows: {before} before, {now} now",
  "fd.guarantee_running": "Guarantee period: day {day} of {total}",
  "fd.guarantee_upcoming": "Guarantee period starts {date}",
  "fd.guarantee_ended": "Guarantee period ended {date}",
  "fd.guarantee_dates": "{start} to {end}",

  // What's working (service status)
  "status.title": "What's working",
  "status.reminders": "Reminders",
  "status.booking": "Booking",
  "status.on": "On",
  "status.waiting": "Waiting",
  "status.setup": "Needs setup",
  "status.check": "Check",
  "status.not_live": "Not live yet",
  "status.web_last": "Last conversation: {when}",
  "status.web_none": "No conversations yet. Is the chat code on your website?",
  "status.web_none_90": "No conversations in the last 90 days. Is the chat code still on your website?",
  "status.web_code_link": "See the chat code",
  "status.web_pending": "Your website chat isn't live yet.",
  "status.sms_last": "Last text from a customer: {when}",
  "status.sms_none": "No texts from customers yet.",
  "status.sms_pending": "Waiting for carrier registration. Texts start once the phone carriers approve your number.",
  "status.sms_setup": "Text messages still need setup. We'll finish it with you.",
  "status.rem_last": "Last reminder sent: {when}",
  "status.rem_none": "No reminders sent yet.",
  "status.rem_count.one": "{n} sent in the last 30 days.",
  "status.rem_count.other": "{n} sent in the last 30 days.",
  "status.rem_setup": "Turned on, but reminders go out by text and text messages aren't ready yet.",
  "status.book_external": "Connected to your booking system.",
  "status.book_link": "Customers get your booking link.",
  "status.book_local": "Your agent books appointments in the conversation.",
  "status.book_external_setup": "Your booking system isn't connected yet.",
  "status.book_link_setup": "No booking link set yet.",

  // Conversation outcomes (Inbox badges, CSV)
  "outcome.booked": "Booked",
  "outcome.booking_link": "Booking link sent",
  "outcome.escalated": "Passed to you",
  "outcome.approval": "Waiting for approval",
  "outcome.blocked": "Blocked",
  "outcome.answered": "Answered",

  // CSV export
  "export.button": "Download CSV",
  "export.menu_title": "Download as a spreadsheet",
  "export.days_30": "Last 30 days",
  "export.days_90": "Last 90 days",
  "export.days_365": "Last 12 months",
  "export.file_conversations": "conversations",
  "export.file_bookings": "bookings",
  "export.col_started": "Started",
  "export.col_last": "Last message",
  "export.col_channel": "Channel",
  "export.col_customer": "Customer",
  "export.col_email": "Email",
  "export.col_phone": "Phone",
  "export.col_messages": "Messages",
  "export.col_outcome": "Outcome",
  "export.col_appointment": "Appointment",
  "export.col_booked_on": "Booked on",
  "export.col_service": "Service or reason",
  "export.col_status": "Status",
  "export.col_source": "Booked through",
  "export.col_reminder": "Reminder sent",
  "export.col_price": "Price (USD)",
  "export.yes": "Yes",
  "export.no": "No",
  "export.source_agent_link": "Your agent (booking link)",
  "export.source_agent": "Your agent",
  "export.source_team": "Your team",
  "export.source_booking_system": "Your booking system",
  "export.status_rescheduled": "Rescheduled",
  "audit.ev.export": "You downloaded a spreadsheet",
};

const ES: Dict = {
  "nav.bandeja": "Bandeja",
  "nav.customers": "Clientes",
  "nav.settings": "Configuración",
  "nav.support": "Soporte",
  "nav.sign_out": "Cerrar sesión",
  "nav.portal": "Portal",
  "session.7day": "Sesión de 7 días",
  "footer.audit": "Cada decisión queda registrada en nuestra cadena de auditoría inmutable.",

  "lang.toggle_label": "Idioma del portal",
  "lang.switch_en": "Ver el portal en inglés",
  "lang.switch_es": "Ver el portal en español",

  "resumen.greeting": "Hola, {name}",
  "resumen.you": "ti",
  "resumen.cta_view_inbox": "Ver bandeja",
  "resumen.status_title": "Estado del servicio",

  "money.alert_title.one": "{n} aprobación esperándote",
  "money.alert_title.other": "{n} aprobaciones esperándote",

  "severity.critical": "Crítico",
  "severity.high": "Alto",
  "severity.medium": "Medio",
  "severity.low": "Bajo",

  "today.title": "Hoy en el calendario",
  "today.empty": "Todavía no hay citas para hoy.",
  "today.more": "+{n} más hoy",

  "live.empty": "Cuando los clientes empiecen a escribirle a tu agente, lo verás aquí.",

  "inbox.title": "Bandeja",
  "inbox.desc": "Todas las conversaciones entre tus clientes y tu agente.",
  "inbox.count.one": "{n} conversación en los últimos 30 días.",
  "inbox.count.other": "{n} conversaciones en los últimos 30 días.",
  "inbox.empty_title": "Sin conversaciones todavía",
  "inbox.empty_desc": "Cuando alguien le escriba a tu agente, la conversación aparece aquí.",
  "inbox.disabled_title": "La bandeja todavía no está activada",
  "inbox.disabled_desc": "El historial de conversaciones todavía no está activado en tu cuenta. Escribe a contact@loucellscore.com y lo activamos.",
  "inbox.select_one": "Elige una conversación a la izquierda.",
  "inbox.filter_all": "Todas",
  "inbox.tags_label": "Etiquetas",
  "inbox.agent_prefix": "Agente: ",
  "inbox.you_prefix": "Tú: ",
  "inbox.messages.one": "{n} mensaje",
  "inbox.messages.other": "{n} mensajes",
  "inbox.message_unavailable": "[mensaje no disponible]",
  "inbox.tag_filter": "Filtrar por etiqueta",
  "inbox.take_over": "Tomar control",
  "inbox.take_over_active": "Estás llevando esta conversación",
  "inbox.take_over_release": "Devolver al agente",
  "inbox.send": "Enviar",
  "inbox.sending": "Enviando…",
  "inbox.composer_placeholder": "Escribe tu mensaje…",
  "inbox.agent_paused": "Agente en pausa. Estás manejando esta conversación a mano.",
  "inbox.sent_email": "Enviado por correo.",
  "inbox.not_delivered_no_contact": "No se envió: este cliente no dejó un correo.",
  "inbox.not_delivered_failed": "No se envió: el correo no pudo salir. Inténtalo de nuevo en un minuto.",
  "inbox.no_contact_notice": "No puedes responder desde aquí: este cliente no dejó un correo, así que tu mensaje nunca le llegaría.",

  "tag.complaint": "Queja",
  "tag.booking": "Cita",
  "tag.info_request": "Información",
  "tag.follow_up": "Seguimiento",
  "tag.spam": "Spam",
  "tag.vip": "VIP",
  "tag.urgent": "Urgente",
  "tag.sale_lost": "Venta perdida",
  "tag.sale_won": "Venta ganada",

  "tool.sent_by": "Enviado por {name}",
  "tool.escalated": "Pasado a tu equipo",
  "tool.booked": "Cita para {name}",
  "tool.refund_blocked": "Reembolso a un destinatario nuevo bloqueado",
  "tool.approval_requested": "Enviado para tu aprobación",
  "tool.approval_skipped": "No se creó la solicitud de aprobación",

  "error.network": "Sin conexión. Revisa tu internet e inténtalo de nuevo.",
  "error.rate_limited": "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.",
  "error.unauthorized": "Tu sesión terminó. Vuelve a iniciar sesión.",
  "error.not_found": "Esto ya no existe. Actualiza la página.",
  "error.bad_request": "No pudimos procesar eso. Revisa el texto e inténtalo de nuevo.",
  "error.service_unavailable": "El servicio no está disponible en este momento. Inténtalo de nuevo en unos minutos.",
  "error.generic": "Algo salió mal. Inténtalo de nuevo o escribe a contact@loucellscore.com.",

  "ra.title": "Aprobaciones",
  "ra.subtitle_pending.one": "{n} acción esperando tu visto bueno.",
  "ra.subtitle_pending.other": "{n} acciones esperando tu visto bueno.",
  "ra.subtitle_empty": "Por ahora no hay nada que decidir.",
  "ra.subtitle_no_agent": "Cuando tu agente necesite tu visto bueno antes de enviar algo, aparece aquí.",
  "ra.history_title": "Historial de decisiones",
  "ra.history_eyebrow": "Últimas 20",
  "ra.clear_title": "Todo en orden",
  "ra.clear_desc": "No hay nada esperando tu aprobación.",
  "ra.action.send_message": "Enviar mensaje",
  "ra.action.send_quote": "Enviar cotización",
  "ra.action.send_refund": "Procesar reembolso",
  "ra.action.reply_review": "Responder reseña",
  "ra.action.other": "Acción del agente",
  "ra.high_risk": "Riesgo alto",
  "ra.medium_risk": "Riesgo medio",
  "ra.proposed_label": "El agente quiere enviar:",
  "ra.edit_label": "Edita el mensaje",
  "ra.reject_label": "¿Por qué? (opcional)",
  "ra.reject_placeholder": "Lo escribiré yo / información incorrecta / no estoy listo todavía",
  "ra.btn_approve": "Aprobar y enviar",
  "ra.btn_modify": "Modificar",
  "ra.btn_reject": "Rechazar",
  "ra.btn_approve_edited": "Aprobar versión editada",
  "ra.btn_confirm_reject": "Confirmar rechazo",
  "ra.btn_cancel": "Cancelar",
  "ra.btn_back": "Atrás",
  "ra.sending": "Enviando…",
  "ra.approving": "Aprobando…",
  "ra.rejecting": "Rechazando…",
  "ra.realtime_hint": "Se envía al instante por correo",
  "ra.stub_hint": "Confirmación en 1 hora hábil",
  "ra.approved_realtime": "Enviado",
  "ra.approved_stub": "Aprobado",
  "ra.approved_realtime_desc": "El mensaje salió al instante.",
  "ra.approved_stub_desc": "Lo estamos haciendo. Recibirás la confirmación en 1 hora hábil.",
  "ra.rejected": "Rechazado",
  "ra.rejected_desc": "El agente no enviará esta acción.",
  "ra.already_title": "Ya resuelta",
  "ra.already_desc": "Esta acción ya fue aprobada o rechazada.",
  "ra.error": "No pudimos procesar la acción. Inténtalo de nuevo o escribe a contact@loucellscore.com.",
  "ra.error_edit_pii": "Tu edición contiene datos sensibles ({types}) que no pueden salir por correo. Quítalos e inténtalo de nuevo.",

  "risk.contains_link": "Contiene un enlace",
  "risk.recipient_unverified": "Destinatario que el cliente no mencionó",
  "risk.pii": "Contiene {type}",

  "pii.ssn": "un número de Seguro Social",
  "pii.ein": "un número fiscal (EIN)",
  "pii.itin": "un número fiscal (ITIN)",
  "pii.credit_card": "un número de tarjeta",
  "pii.email": "un correo electrónico",
  "pii.us_phone": "un número de teléfono",
  "pii.api_key": "una clave de acceso",
  "pii.other": "datos personales",

  "customers.title": "Clientes",
  "customers.desc": "Todas las personas que le han escrito a tu agente, por el chat del sitio o por mensaje de texto.",
  "customers.empty_title": "Sin clientes todavía",
  "customers.empty_desc": "Cuando la gente empiece a escribirle a tu agente, cada persona aparece aquí con su historial.",
  "customers.count.one": "{n} persona",
  "customers.count.other": "{n} personas",
  "customers.col_sessions": "Sesiones",
  "customers.col_bookings": "Citas",

  "customer.back": "Todos los clientes",
  "customer.history_title": "Historial de conversaciones",
  "customer.bookings_title": "Citas",
  "customer.notes_title": "Notas internas",
  "customer.notes_empty": "Sin notas todavía. Puedes agregar una cuando quieras.",
  "customer.notes_error": "No se pudo guardar la nota. Inténtalo de nuevo.",
  "customer.seen": "Primer contacto {first} · Último contacto {last}",
  "customer.channels": "Canales",
  "customer.entries.one": "{n} registro",
  "customer.entries.other": "{n} registros",
  "customer.no_conv_title": "Sin conversaciones todavía",
  "customer.no_conv_desc": "Cuando este cliente vuelva a escribir, aparecerá aquí.",
  "customer.no_reason": "Sin motivo registrado",
  "customer.channel": "Canal: {channel}",
  "customer.open_chat": "Abrir conversación",
  "customer.confirmed_count.one": "{n} confirmada",
  "customer.confirmed_count.other": "{n} confirmadas",
  "customer.no_bookings": "Sin citas todavía",
  "customer.confirmed_on": "Confirmada el {date}",
  "customer.confirmed": "Confirmada",

  "channel.web_chat": "Chat del sitio web",
  "channel.website": "Formulario del sitio web",
  "channel.sms": "Mensajes de texto",
  "channel.whatsapp": "WhatsApp",
  "channel.email": "Correo",
  "channel.phone": "Teléfono",
  "channel.gbp": "Reseñas de Google",
  "channel.slack": "Slack",
  "channel.other": "Otro",

  "agents.empty_title": "Todavía no hay agentes",
  "agents.empty_desc": "Cuando Loucells Core configure un agente para ti, aparecerá aquí con lo que hace y los resultados que logra.",

  "agent_status.designing": "En configuración",
  "agent_status.shadow_mode": "En observación",
  "agent_status.uat": "En pruebas",
  "agent_status.live": "Activo",
  "agent_status.paused": "En pausa",
  "agent_status.archived": "Retirado",
  "agent_status.other": "En proceso",

  "agent_type.ai_front_desk": "Recepción",
  "agent_type.quote_accelerator": "Cotizaciones",
  "agent_type.review_manager": "Reseñas",
  "agent_type.operations_gap_audit": "Revisión de operaciones",
  "agent_type.custom": "Agente a la medida",

  "integration.calendar": "Calendario",
  "integration.booking": "Sistema de citas",
  "integration.crm": "CRM",
  "integration.reminders": "Recordatorios de citas",
  "integration.whatsapp": "WhatsApp",
  "integration.sms": "Mensajes de texto",
  "integration.email": "Correo",
  "integration.payments": "Pagos",
  "integration.reviews": "Reseñas",

  "audit.ev.user_message": "Mensaje de cliente recibido",
  "audit.ev.assistant_reply": "El agente respondió",
  "audit.ev.escalation": "Pasado a tu equipo",
  "audit.ev.booking_offered": "Enlace para agendar enviado",
  "audit.ev.approval_requested": "Enviado para tu aprobación",
  "audit.ev.queue_full": "Demasiadas acciones esperando tu aprobación",
  "audit.ev.hitl_approved": "Aprobaste una acción",
  "audit.ev.hitl_rejected": "Rechazaste una acción",
  "audit.ev.action_failed": "Una acción aprobada no se pudo completar",
  "audit.ev.take_over": "Respondiste personalmente",
  "audit.ev.paused": "Agente en pausa mientras atiendes la conversación",
  "audit.ev.sensitive_blocked": "Mensaje con datos sensibles bloqueado",
  "audit.ev.sensitive_hidden": "Datos sensibles ocultados",
  "audit.ev.rate_limited": "Demasiados mensajes en poco tiempo",
  "audit.ev.origin_blocked": "Bloqueado desde un sitio web que no es tuyo",
  "audit.ev.unavailable": "El agente no pudo responder",
  "audit.ev.hard_rule": "Respuesta ajustada por las reglas de seguridad",
  "audit.ev.refund_blocked": "Reembolso a un destinatario nuevo bloqueado",
  "audit.ev.config_update": "Configuración del agente actualizada",
  "audit.ev.other": "Evento del sistema",
  "audit.src.agent": "Agente",
  "audit.src.portal": "Portal",
  "audit.src.hitl": "Aprobaciones",
  "audit.src.dlp": "Protección de datos",
  "audit.src.webhook": "Herramienta conectada",
  "audit.src.security": "Seguridad",
  "audit.src.other": "Sistema",

  "analytics.hourly_title": "Cuándo te contactan",
  "analytics.hourly_desc": "Mensajes de clientes según la hora de tu día.",
  "analytics.topics_title": "Sobre qué preguntan",
  "analytics.topics_desc": "Agrupado por el primer mensaje de cada conversación.",

  "settings.title": "Configuración",
  "settings.desc": "Tu plan, tu agente y el idioma del portal.",
  "settings.tab_billing": "Plan",
  "settings.tab_language": "Idioma",
  "settings.plan_title": "Tu plan con Loucells Core",
  "settings.plan_eyebrow": "Resumen mensual",
  "settings.plan_monthly": "Costo mensual",
  "settings.plan_monthly_sub": "Tarifa mensual fija. Incluye hospedaje, mantenimiento y soporte.",
  "settings.plan_agents": "Agentes incluidos",
  "settings.plan_client_since": "Cliente desde",
  "settings.plan_portal_activated": "Portal activado {date}",
  "settings.includes_title": "Qué incluye",
  "settings.includes_eyebrow": "Incluido en tu plan",
  "settings.account_title": "Datos de tu cuenta",
  "settings.account_eyebrow": "Información de contacto",
  "settings.account_legal": "Razón social",
  "settings.account_vertical": "Vertical",
  "settings.account_language": "Idioma",
  "settings.account_email": "Correo de facturación",
  "settings.account_update": "Actualizar datos",
  "settings.billing_help": "¿Dudas sobre tu factura? Escribe a contact@loucellscore.com.",
  "settings.lang_title": "Idioma del portal",
  "settings.lang_desc": "Se aplica a todas las páginas del portal.",
  "settings.lang_en": "Inglés",
  "settings.lang_es": "Español",
  "settings.lang_save": "Guardar preferencia",
  "settings.lang_saved": "Guardado",

  "login.title": "Hola de nuevo",
  "login.desc": "Ingresa el código de acceso que te dio Loucells Core para entrar a tu portal.",
  "login.inside": "Lo que verás adentro",
  "login.inside_conversations": "Tus conversaciones",
  "login.inside_approvals": "Aprobaciones",
  "login.inside_customers": "Tus clientes",
  "login.inside_log": "Registro de actividad",
  "login.passcode": "Código de acceso",
  "login.placeholder": "Pega el código aquí",
  "login.submit": "Entrar al portal",
  "login.submitting": "Entrando…",
  "login.err_rate": "Demasiados intentos. Inténtalo de nuevo en unos minutos.",
  "login.err_bad": "Ese código no coincide. Revisa el mensaje que te envió Loucells Core.",
  "login.err_generic": "No pudimos iniciar tu sesión. Inténtalo de nuevo o escribe a contact@loucellscore.com.",
  "login.err_network": "Sin conexión. Revisa tu internet e inténtalo de nuevo.",
  "login.footnote": "Tu sesión dura 7 días. Las conversaciones se guardan cifradas y los datos personales se ocultan antes de llegar al registro de actividad.",

  "btn.save": "Guardar",

  "nav.open_menu": "Abrir menú",
  "nav.close_menu": "Cerrar menú",

  "nav.home": "Inicio",
  "nav.approvals": "Aprobaciones",

  "home.eyebrow": "Últimos {n} días",
  "home.desc": "Primero lo que necesita tu atención. Abajo, lo que tu agente hizo por {client}.",
  "home.needs_title": "Te necesita",
  "home.needs_clear": "Nada necesita tu atención ahora.",
  "home.needs_clear_desc": "Tu agente está atendiendo todo dentro de las reglas que aprobaste.",
  "home.see_all.one": "Ver {n} aprobación",
  "home.see_all.other": "Ver las {n} aprobaciones",
  "home.escalations.one": "{n} cliente necesita a una persona",
  "home.escalations.other": "{n} clientes necesitan a una persona",
  "home.takeovers.one": "{n} conversación que estás atendiendo tú",
  "home.takeovers.other": "{n} conversaciones que estás atendiendo tú",
  "home.takeover_hint": "Tu agente no responde en estas hasta que se las devuelvas.",
  "home.open": "Abrir",
  "home.recent_title": "Conversaciones recientes",
  "home.insights_eyebrow": "Últimos 30 días",
  "home.peak_hour": "Hora con más mensajes: {hour}",

  "badge.web": "Web",
  "badge.sms": "SMS",

  "topic.booking": "Citas",
  "topic.pricing": "Precios",
  "topic.hours": "Horario y ubicación",
  "topic.service_info": "Preguntas sobre un servicio",
  "topic.complaint": "Problemas o quejas",
  "topic.other": "Otros",

  "escalation.reason.out_of_scope": "Preguntó por algo que tu agente no atiende",
  "escalation.reason.sensitive_topic": "Un tema delicado",
  "escalation.reason.frustrated_visitor": "El cliente parece molesto",
  "escalation.reason.ambiguous_high_stakes": "Un pedido importante que necesita tu decisión",
  "escalation.reason.agent_uncertain": "Tu agente no estaba seguro de cómo responder",
  "escalation.reason.other": "Necesita a una persona",

  "inbox.filter_taken": "Tomadas por ti",
  "inbox.filter_urgent": "Urgentes",
  "inbox.filter_booked": "Con cita",
  "inbox.any_tag": "Cualquier etiqueta",
  "inbox.filter_empty": "Ninguna conversación coincide con este filtro.",
  "inbox.window_empty": "No hay conversaciones en los últimos 30 días.",
  "inbox.web_visitor": "Visitante del sitio web",
  "inbox.back": "Todas las conversaciones",
  "inbox.sms_readonly": "Por ahora responde desde tu teléfono.",
  "inbox.text_customer": "Escribir a {phone}",
  "inbox.not_delivered": "No se entregó",
  "inbox.badge_taken": "La atiendes tú",
  "inbox.badge_urgent": "Urgente",
  "inbox.not_found": "No encontramos esta conversación. Puede tener más de 30 días.",

  "ra.open_conversation": "Abrir conversación",
  "ra.outcome.sent": "Enviado",
  "ra.outcome.handling": "En proceso",
  "ra.outcome.failed": "Falló",
  "ra.outcome.rejected": "Rechazado",
  "ra.history_note": "Enviado: ya salió. En proceso: lo estamos haciendo por ti. Falló: no salió, escribe a contact@loucellscore.com.",

  "customers.conversations.one": "{n} conversación",
  "customers.conversations.other": "{n} conversaciones",
  "customers.bookings.one": "{n} cita",
  "customers.bookings.other": "{n} citas",
  "customers.last_contact": "Último contacto: {date}",
  "customers.no_name": "Sin nombre todavía",

  "customer.text_title": "Mensajes de texto",
  "customer.open_texts": "Abrir conversación por SMS",
  "customer.appt.scheduled": "Agendada",
  "customer.appt.confirmed": "Confirmada",
  "customer.appt.completed": "Realizada",
  "customer.appt.cancelled": "Cancelada",
  "customer.appt.no_show": "No se presentó",

  "settings.tab_agent": "Tu agente",
  "settings.agent_live_since": "En vivo desde el {date}",
  "settings.agent_connections": "Herramientas conectadas",
  "settings.conn_connected": "Conectada",
  "settings.conn_missing": "Sin conectar todavía",
  "settings.conn_since": "Desde el {date}",
  "settings.conn_none": "Todavía no hay herramientas conectadas.",
  "settings.conn_missing_help": "Las conectamos contigo. Escribe a contact@loucellscore.com.",
  "settings.agent_change": "¿Quieres cambiar algo? Escribe a contact@loucellscore.com.",

  "conn.sms": "Mensajes de texto",
  "conn.booking_system": "Tu sistema de reservas",
  "conn.reviews": "Reseñas de Google",
  "conn.payments": "Pagos",
  "conn.crm": "Lista de clientes (CRM)",
  "conn.accounting": "Contabilidad",
  "conn.field_service": "Gestión de trabajos",
  "conn.email": "Correo",
  "conn.microsoft": "Correo y calendario de Microsoft",
  "conn.other": "Otra herramienta",

  "embed.title": "Código del chat para tu sitio",
  "embed.desc": "Pégalo justo antes de </body> en cada página donde quieras el chat.",
  "embed.live": "En vivo",
  "embed.not_live": "Todavía no está en vivo",
  "embed.copy": "Copiar",
  "embed.copied": "Copiado",
  "embed.copy_aria": "Copiar el código",
  "embed.domains": "Sitios donde funciona",
  "embed.domains_desc": "El chat solo carga en estos sitios. Para agregar o quitar uno, escríbenos.",
  "embed.domains_none": "Todavía no hay sitios agregados. El chat no cargará hasta que agreguemos al menos uno.",
  // ── Resultados (Inicio, valor en dinero y resultados) ─────────────
  "home.results_title": "Resultados",
  "home.window_label": "Periodo",
  "home.window_days": "{n} días",
  "value.bookings": "Citas gracias a tu agente",
  "value.revenue": "Ingresos de citas realizadas",
  "value.conversations": "Conversaciones",
  "value.window_sub": "Últimos {n} días",
  "value.rule": "Los ingresos solo cuentan citas realizadas en las que el cliente habló primero con tu agente. Las citas protegidas por un recordatorio se cuentan aparte y nunca se suman a los ingresos.",
  "value.unpriced.one": "{n} cita de este periodo no tiene precio, así que su valor no se cuenta.",
  "value.unpriced.other": "{n} citas de este periodo no tienen precio, así que su valor no se cuenta.",
  "value.after_hours.one": "Fuera de tu horario: {a} de {n} conversación.",
  "value.after_hours.other": "Fuera de tu horario: {a} de {n} conversaciones.",
  "value.reply_time": "Tiempo habitual de respuesta a los textos: {time}.",
  "value.seconds.one": "{n} segundo",
  "value.seconds.other": "{n} segundos",
  "value.minutes.one": "{n} minuto",
  "value.minutes.other": "{n} minutos",
  "value.hours_estimate": "Unas {h} horas de trabajo de recepción ahorradas. Estimado: {n} min por conversación.",
  "value.hours_estimate_mixed": "Unas {h} horas de trabajo de recepción ahorradas (estimado).",
  "value.unavailable": "No pudimos cargar estos números ahora. Vuelve a cargar en un minuto.",

  // Resultados de recepción
  "fd.title": "Resultados de recepción",
  "fd.reminders_sent": "Recordatorios enviados",
  "fd.kept": "Cumplidas",
  "fd.no_shows": "Ausencias",
  "fd.no_show_rate": "Tasa de ausencias",
  "fd.rate_none": "Aún no",
  "fd.note": "Cumplidas y ausencias son citas que recibieron un recordatorio. La tasa de ausencias incluye todas las citas ya pasadas de este periodo.",
  "fd.protected": "Citas protegidas por un recordatorio: {n}. Se cuentan aquí, nunca se suman a los ingresos.",
  "fd.before_now": "Ausencias: {before} antes, {now} ahora",
  "fd.guarantee_running": "Periodo de garantía: día {day} de {total}",
  "fd.guarantee_upcoming": "El periodo de garantía empieza el {date}",
  "fd.guarantee_ended": "El periodo de garantía terminó el {date}",
  "fd.guarantee_dates": "Del {start} al {end}",

  // Qué está funcionando (estado del servicio)
  "status.title": "Qué está funcionando",
  "status.reminders": "Recordatorios",
  "status.booking": "Reservas",
  "status.on": "Activo",
  "status.waiting": "En espera",
  "status.setup": "Falta configurar",
  "status.check": "Revisar",
  "status.not_live": "Aún no está en vivo",
  "status.web_last": "Última conversación: {when}",
  "status.web_none": "Todavía no hay conversaciones. ¿Está el código del chat en tu sitio web?",
  "status.web_none_90": "No hay conversaciones en los últimos 90 días. ¿Sigue el código del chat en tu sitio web?",
  "status.web_code_link": "Ver el código del chat",
  "status.web_pending": "El chat de tu sitio todavía no está en vivo.",
  "status.sms_last": "Último texto de un cliente: {when}",
  "status.sms_none": "Todavía no hay textos de clientes.",
  "status.sms_pending": "Esperando el registro con las compañías telefónicas. Los textos empiezan cuando aprueben tu número.",
  "status.sms_setup": "Los mensajes de texto todavía necesitan configuración. Lo terminamos contigo.",
  "status.rem_last": "Último recordatorio enviado: {when}",
  "status.rem_none": "Todavía no se ha enviado ningún recordatorio.",
  "status.rem_count.one": "{n} enviado en los últimos 30 días.",
  "status.rem_count.other": "{n} enviados en los últimos 30 días.",
  "status.rem_setup": "Están activados, pero los recordatorios salen por texto y los mensajes de texto todavía no están listos.",
  "status.book_external": "Conectado a tu sistema de reservas.",
  "status.book_link": "Los clientes reciben tu enlace para reservar.",
  "status.book_local": "Tu agente agenda las citas en la conversación.",
  "status.book_external_setup": "Tu sistema de reservas todavía no está conectado.",
  "status.book_link_setup": "Todavía no hay un enlace para reservar.",

  // Resultado de cada conversación (Bandeja, CSV)
  "outcome.booked": "Con cita",
  "outcome.booking_link": "Enlace de reserva enviado",
  "outcome.escalated": "Pasada a ti",
  "outcome.approval": "Esperando aprobación",
  "outcome.blocked": "Bloqueada",
  "outcome.answered": "Respondida",

  // Exportar CSV
  "export.button": "Descargar CSV",
  "export.menu_title": "Descargar como hoja de cálculo",
  "export.days_30": "Últimos 30 días",
  "export.days_90": "Últimos 90 días",
  "export.days_365": "Últimos 12 meses",
  "export.file_conversations": "conversaciones",
  "export.file_bookings": "citas",
  "export.col_started": "Inicio",
  "export.col_last": "Último mensaje",
  "export.col_channel": "Canal",
  "export.col_customer": "Cliente",
  "export.col_email": "Correo",
  "export.col_phone": "Teléfono",
  "export.col_messages": "Mensajes",
  "export.col_outcome": "Resultado",
  "export.col_appointment": "Cita",
  "export.col_booked_on": "Reservada el",
  "export.col_service": "Servicio o motivo",
  "export.col_status": "Estado",
  "export.col_source": "Reservada por",
  "export.col_reminder": "Recordatorio enviado",
  "export.col_price": "Precio (USD)",
  "export.yes": "Sí",
  "export.no": "No",
  "export.source_agent_link": "Tu agente (enlace de reserva)",
  "export.source_agent": "Tu agente",
  "export.source_team": "Tu equipo",
  "export.source_booking_system": "Tu sistema de reservas",
  "export.status_rescheduled": "Reprogramada",
  "audit.ev.export": "Descargaste una hoja de cálculo",
};

const DICTS: Record<PortalLang, Dict> = { en: EN, es: ES };

export function t(lang: PortalLang, key: string, params?: Record<string, string | number>): string {
  const raw = DICTS[lang]?.[key] ?? DICTS.en[key] ?? key;
  if (!params) return raw;
  return raw.replace(/\{(\w+)\}/g, (_m, k: string) => {
    const v = params[k];
    return v === undefined ? `{${k}}` : String(v);
  });
}

/**
 * Count-aware lookup: reads `<key>.one` when n is 1 and `<key>.other`
 * otherwise, with {n} filled in. EN and ES both use one/other, which is
 * all the CLDR categories these two languages need for integer counts.
 */
export function tn(
  lang: PortalLang,
  key: string,
  n: number,
  params?: Record<string, string | number>,
): string {
  return t(lang, `${key}.${n === 1 ? "one" : "other"}`, { n, ...params });
}

/** All keys defined for a language. Used by tests to check EN/ES parity. */
export function portalStringKeys(lang: PortalLang): string[] {
  return Object.keys(DICTS[lang]);
}
